### ISSUE TITLE
Money and SUMs

### ISSUE THREAD

**Issue by aphillipo** [kipcole9/money#13]
Hi there Kip Cole!

This library is fantastic - what do you think about allowing the exchange rates to be written to the database to facilitate doing conversions and then SUMs/aggregate functions in the database (converting everything to a specific currency before SUM would be possible then)?  This might be a terrible idea but it feels better than getting much larger result sets and reducing everything?

**Comment by kipcole9** [comment]
Andrew, thanks for the feedback.

Serialization of exchange rates is the idea behind having a `callback_module` configuration option.  There are a lot of ways the data could be stored so rather than fix on one the idea is that you configure a callback in `config.exs` per:

```
config :ex_money,
  callback_module: Money.ExchangeRates.Callback,
l
```
> callback_module defines a module that follows the Money.ExchangeRates.Callback behaviour whereby the function rates_retrieved/2 is invoked after every successful retrieval of exchange rates. The default is Money.ExchangeRates.Callback.

Then in that module you can store the rates in a database after each successful retrieval.

**Does that cater for your needs?**  Very open to other ideas that would make life easier working with rates.

In a business I work with there is definitely a requirement to store rates, associate names with rates (like `2017_budget_rate`, `2017_march_forecast_rate` and so on) and do comparison or FX effects too. 

I don't think thats general use enough for that functionality to be core to the lib.  Let me know if you think otherwise?

**Comment by aphillipo** [comment]
That’s brilliant thank you!  Always one step ahead 👍🏻
