### ISSUE TITLE
Casting a money type with a default_currency option?

### ISSUE THREAD

**Issue by agatheblues** [kipcole9/money#133]
Hello! 

First of all, well done & thank you for your work 🙌 🍭 

Recently I ran into an issue, where a price form field would get automatically converted to dollars, when the user would not specify a currency. For example, entering "500" in the text field would be saved as `#Money<:USD, 500>`. 

If I'm not mistaken, the `:USD` currency code is derived from `Cldr.Currency.currency_from_locale(locale)`. In my case the locale is set from `Cldr.Plug.AcceptLanguage`, which is `en`, thus, the dollars. The problem is that dollars do not really make sense in the app I'm working on: I'd rather default to `:EUR`, unless specified by the user.

I ended up manually parsing before casting in my changeset, with `Money.parse(value, default_currency: :EUR)`, but that feels a lot like a hack.  Thus my initial question: would it be possible to pass a `default_currency` option to the `Money.Ecto.Composite.Type` cast implementation (and does it make sense?)? 

Or should that rather be solved on CLDR side (if it is possible to override which currency is used for which locale for example)? Or the last resort would be to use two input fields, one with the amount and the other with the currency?

Thanks for your help ⭐

**Comment by kipcole9** [comment]
Thanks for the feedback and support, its much appreciated.

UX for entering money amounts is one area I know needs work. I'm optimistic that a Liveview Component might be helpful but I haven't made that a priority. Perhaps I should.

Under the covers, `Money.Ecto.Composite.Type` does in fact call `Money.parse/2` with casting a `String.t` so ultimately that is the right path. And indeed parameters can be provided to that function. For example:
```elixir
iex> Money.Ecto.Composite.Type.cast "500", default_currency: :EUR
{:ok, #Money<:EUR, 500>}
```
But using `Ecto.Changest.cast/3` isn't going to pass the options I think?  Meaning I don't think the following works? (I will test it later)
```elixir
  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:money], default_currency: :EUR)
    ...
  end
```
The other suggestions you made are options I've also been thinking about. But let me first test whether options to `cast/4` actually get passed to custom types because if so I think that will be the cleanest solution.

**Comment by kipcole9** [comment]
OK, after further research my current recommendation is to set the default currency on the schema. For example, using the schema I have for testing:
```elixir
defmodule Organization do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  schema "organizations" do
    field :payroll,         Money.Ecto.Composite.Type, default_currency: :JPY
    field :tax,             Money.Ecto.Composite.Type, fractional_digits: 4
    field :value,           Money.Ecto.Composite.Type, default: Money.new(:USD, 0)
    field :name,            :string
    field :employee_count,  :integer
    timestamps()
  end

  def changeset(organization, params \\ %{}) do
    organization
    |> cast(params, [:payroll])
  end
end
```
You can see I have set a `:default_currency` on a schema field and this is passed to the `cast/4` function in the changeset. [This test]() shows an example.

Let me know if that works well enough for you?

**Comment by kipcole9** [comment]
I have also updated the documentation to describe [working with schemas and changesets](https://hexdocs.pm/ex_money_sql/readme.html#casting-money-with-changesets).

**Comment by kipcole9** [comment]
Cool, happy that meets your needs and it was only a doc change!  Feel free to let me know what else you need. I'll close this issue but reopen if required.
