### ISSUE TITLE
Errors on upgrade

### ISSUE THREAD

**Issue by coladarci** [kipcole9/money#150]
Heyya - 

When running the following update:
```
  ex_money 5.12.3 => 5.13.0
  ex_money_sql 1.8.0 => 1.9.2
```
I suddenly get the following:
```
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for {"USD", Decimal.new("50.00")} of type Tuple
```

There isn't a good stack trace to point to anything specific, but I'm hoping you have some ideas? 

Here are all our deps:
```
 absinthe 1.7.4 
 absinthe_phoenix 2.0.2 
 absinthe_plug 1.5.8 
 bamboo 2.1.0 
 bamboo_smtp 4.0.1 
 bunt 0.2.1 
 castore 0.1.22 
 certifi 2.9.0 
 cldr_utils 2.24.1 
 cloak 1.1.2 
 cloak_ecto 1.2.0 
 cors_plug 3.0.3 
 cowboy 2.10.0 
 cowboy_telemetry 0.3.1 
 cowlib 2.12.1 
 credo 1.7.0 
 dataloader 1.0.10 
 db_connection 2.5.0 
 decimal 2.1.1 
 dialyxir 1.1.0 
 digital_token 0.6.0 
 ecto 3.10.3 
 ecto_enum 1.4.0 
 ecto_hashids 0.0.1 
 ecto_sql 3.10.1 
 erlex 0.2.6 
 ex_cldr 2.37.2 
 ex_cldr_calendars 1.22.1 
 ex_cldr_currencies 2.15.0 
 ex_cldr_dates_times 2.13.3 
 ex_cldr_locale_display 1.4.0 
 ex_cldr_numbers 2.31.2 
 ex_cldr_territories 2.7.0 
 ex_money 5.13.0 
 ex_money_sql 1.9.2 
 expo 0.4.1 
 file_system 0.2.10 
 gen_smtp 1.1.1 
 gettext 0.22.3 
 hackney 1.18.1 
 hammer 6.0.0 
 hammer_backend_redis 6.1.0 
 hashids 2.1.0 
 httpoison 2.1.0 
 hut 1.3.0 
 idna 6.1.1 
 jason 1.4.1 
 joken 2.6.0 
 jose 1.11.5 
 libcluster 3.3.2 
 metrics 1.0.1 
 mime 1.6.0 
 mimerl 1.2.0 
 mix_test_watch 1.1.0 
 neuron 5.1.0 
 new_relic_absinthe 0.0.4 
 new_relic_agent 1.27.8 
 nimble_parsec 1.3.1 
 oban 2.15.2 
 oban_pro 1.0.0 (oban
 oban_web 2.9.7 (oban
 parse_trans 3.3.1 
 phoenix 1.7.7 
 phoenix_ecto 4.4.2 
 phoenix_html 3.3.1 
 phoenix_live_dashboard 0.8.0 
 phoenix_live_view 0.19.4 
 phoenix_pubsub 2.1.3 
 phoenix_template 1.0.2 
 phoenix_view 2.0.2 
 plug 1.14.2 
 plug_cowboy 2.6.1 
 plug_crypto 1.2.5 
 poolboy 1.5.2 
 postgrex 0.17.1 
 ranch 1.8.0 
 redix 0.11.2 
 retry 0.17.0 
 scrivener 2.7.2 
 scrivener_ecto 2.7.0 
 segment 0.2.7 
 sentry 8.0.6 
 ssl_verify_fun 1.1.6 
 telemetry 0.4.3 
 telemetry_metrics 0.6.1 
 telemetry_poller 0.5.1 
 tesla 1.7.0 
 tzdata 1.1.1 
 unicode_util_compat 0.7.0 
 websock 0.5.2 
 websock_adapter 0.5.3 
 absinthe 1.7.4 
 absinthe_phoenix 2.0.2 
 absinthe_plug 1.5.8 
 bamboo 2.1.0 
 bamboo_smtp 4.0.1 
 bunt 0.2.1 
 castore 0.1.22 
 certifi 2.9.0 
 cldr_utils 2.24.1 
 cloak 1.1.2 
 cloak_ecto 1.2.0 
 cors_plug 3.0.3 
 cowboy 2.10.0 
 cowboy_telemetry 0.3.1 
 cowlib 2.12.1 
 credo 1.7.0 
 dataloader 1.0.10 
 db_connection 2.5.0 
 decimal 2.1.1 
 dialyxir 1.1.0 
 digital_token 0.6.0 
 ecto 3.10.3 
 ecto_enum 1.4.0 
 ecto_hashids 0.0.1 
 ecto_sql 3.10.1 
 erlex 0.2.6 
 ex_cldr 2.37.2 
 ex_cldr_calendars 1.22.1 
 ex_cldr_currencies 2.15.0 
 ex_cldr_dates_times 2.13.3 
 ex_cldr_locale_display 1.4.0 
 ex_cldr_numbers 2.31.2 
 ex_cldr_territories 2.7.0 
 ex_money 5.13.0 
 ex_money_sql 1.9.2 
 expo 0.4.1 
 file_system 0.2.10 
 gen_smtp 1.1.1 
 gettext 0.22.3 
 hackney 1.18.1 
 hammer 6.0.0 
 hammer_backend_redis 6.1.0 
 hashids 2.1.0 
 httpoison 2.1.0 
 hut 1.3.0 
 idna 6.1.1 
 jason 1.4.1 
 joken 2.6.0 
 jose 1.11.5 
 libcluster 3.3.2 
 metrics 1.0.1 
 mime 1.6.0 
 mimerl 1.2.0 
 mix_test_watch 1.1.0 
 neuron 5.1.0 
 new_relic_absinthe 0.0.4 
 new_relic_agent 1.27.8 
 nimble_parsec 1.3.1 
 oban 2.15.2 
 oban_pro 1.0.0 (oban
 oban_web 2.9.7 (oban
 parse_trans 3.3.1 
 phoenix 1.7.7 
 phoenix_ecto 4.4.2 
 phoenix_html 3.3.1 
 phoenix_live_dashboard 0.8.0 
 phoenix_live_view 0.19.4 
 phoenix_pubsub 2.1.3 
 phoenix_template 1.0.2 
 phoenix_view 2.0.2 
 plug 1.14.2 
 plug_cowboy 2.6.1 
 plug_crypto 1.2.5 
 poolboy 1.5.2 
 postgrex 0.17.1 
 ranch 1.8.0 
 redix 0.11.2 
 retry 0.17.0 
 scrivener 2.7.2 
 scrivener_ecto 2.7.0 
 segment 0.2.7 
 sentry 8.0.6 
 ssl_verify_fun 1.1.6 
 telemetry 0.4.3 
 telemetry_metrics 0.6.1 
 telemetry_poller 0.5.1 
 tesla 1.7.0 
 tzdata 1.1.1 
 unicode_util_compat 0.7.0 
 websock 0.5.2 
 websock_adapter 0.5.3 
```

Appreciate any ideas!

**Comment by kipcole9** [comment]
Apologies, that's extremely inconvenient.

The type `{"USD", Decimal.new("50.00")}` is the format that comes back from `Postgrex` for the `money_with_currency` composite type in Postgres.  Is that correct in your case?

If so, the likely culprit is `ex_money_sql` and as a first measure I'd recommend first moving back to `ex_money_sql 1.9.0`. 

There were some changes to the type definition in 1.9.2 that related to embedded schemas. By any chance would you be using embedded schemas with a money type in Postgres? That would be a second line of enquiry. Because `money_sql` itself doesn't use JSON encoding directly - it's only (as I understand it) when `Ecto` is encoding a `map()` type field or an embedded schema.

Hope that gives you a more specific place to look and one thing to try.  If you are able to isolate the Ecto schema that is raising the issue and you are able to share it that would be extremely helpful.

**Comment by coladarci** [comment]
Thanks! Yes we definitely embed Money Objects - we can try rolling back, but what can I do to help sort out the potential bug around embedded moneys?

**Comment by kipcole9** [comment]
My guess (and it's a guess) is that in your embedded schemas the type is `Money.Ecto.Composite.Type` when it needs to be `Money.Ecto.Map.Type`. It seems to have worked a bit by accident in earlier releases and I didn't have good enough test coverage.

I merged a [PR](https://github.com/kipcole9/money_sql/pull/32) that fixed some issues with embedded schemas but it may have introduced the issue you are seeing.  If `money_sql` version 1.9.1 works but 1.9.2 doesn't then that helps narrow down where to look.  I'm a little surprised though because the tuple form like `{"USD", Decimal.new("50.00")}` can only come from the composite type.

### Summary

1. An embedded money type needs to be `Money.Ecto.Map.Type` like this:
```elixir
  schema "organizations" do
    embeds_many :customers, Customer do
      field :name, :string
      field :revenue, Money.Ecto.Map.Type, default: Money.new(:USD, 0)
    end
  end
```

2. If `1.9.1` works and `1.9.2` doesn't then its isolated to the referenced PR and I have at least somewhere to start looking.
3.

**Comment by coladarci** [comment]
I can confirm that flipping to `Money.Ecto.Map.Type` solves my problems!

**Comment by kipcole9** [comment]
Phew, extremely happy to hear that.  I will make a much clearer note in the readme and the changelog.  The previous behaviour was erroneous and I'm surprised it actually worked - but clearly not a great upgrade experience.

**Comment by coladarci** [comment]
What made this wonderful is that I had zero doubt you'd have an answer within 24 hours (and more likely within a few) and you did not disappoint. I appreciate you and this library more than you can know!

**Comment by kipcole9** [comment]
Thanks for the kind words Greg, it's much appreciated and definitely keeps my. motivation high.
