### ISSUE TITLE
Using MyApp.Repo inside callback_module

### ISSUE THREAD

**Issue by aphillipo** [kipcole9/money#16]
So I configured my callback_module and it has the following code:

```elixir
  @spec rates_retrieved(%{}, %DateTime{}) :: :ok
  def rates_retrieved(rates, _retrieved_at) do
    # just write the exchange rates every time, on_conflict -> upsert. 
    MyApp.Repo.insert_all(
      MyApp.Publisher.ExchangeRates, 
      rates |> Enum.map(fn({k, v}) -> 
        %{currency: Atom.to_string(k), rate: v}
      end),
      conflict_target: :currency,
      on_conflict: :replace_all
    )
    :ok
  end
```

However, it seems rates are retrieved during the app initialisation process, before MyApp.Repo is started causing everything to fail.  Any ideas what to do to make sure MyApp.Repo is started (I have tried MyApp.Repo.start_link but this causes other issues).  

Here is the Error I'm getting:

```
frontend_1    | 08:34:56.112 [info] Starting exchange rate retrieval service
frontend_1    | 08:34:56.115 [info] Rates will be retrieved every 3600 seconds.
frontend_1    |
frontend_1    | =INFO REPORT==== 22-Jun-2017::08:34:57 ===
frontend_1    |     application: logger
frontend_1    |     exited: stopped
frontend_1    |     type: temporary
frontend_1    | ** (Mix) Could not start application ex_money: Money.start(:normal, []) returned an error: shutdown: failed to start child: Money.ExchangeRates.Supervisor
frontend_1    |     ** (EXIT) shutdown: failed to start child: Money.ExchangeRates.Retriever
frontend_1    |         ** (EXIT) exited in: :gen_server.call(PayPip.Repo.Pool, {:checkout, #Reference<0.3117745951.3369598977.110941>, true}, 5000)
frontend_1    |             ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Thanks for your help on this!

**Comment by kipcole9** [comment]
Andrew, on reflection I think the issue is deeper.  I need to change two things:

1. Its not a good idea to do retrieval from the `init/1` function of the retriever.  Too easy to crash the retriever and supervisor. 

2. Since there may be dependencies on the start order of the supervision tree, this should be in the control of the hosting app, not `ex_money`.  Or at least optional.  In your case, `Ecto.Repo` is the start dependency but there of course could be arbitrary dependencies I can't predict.

One open issue I need to work out is how (if?) to preserve the guarantee that exchange rates are available after the retriever starts up.

I'll start refactoring this but don't expect I'll complete an update and tests until Saturday.  Thoughts and ideas welcome.

**Comment by aphillipo** [comment]
Hi there, no worries about timing; I have managed to hack a list of exchange rates into the DB which allows me to write my queries correctly.

I'm afraid I definitely am not at the level where I can help directly on this but thanks so much for the library and helping with this! Let me know if there are any smaller sub tasks that I could do and I'll take a look!

**Comment by kipcole9** [comment]
Andrew, looked into this and its a simple configuration change in your app to fix the sequence of app startup.  I've tested this in version 0.1.7 and the upcoming version 0.20 that I expect to publish later today.  From the forthcoming update to the readme.md:

## Using Ecto or other applications from within the callback module

If you provide your own callback module and that module depends on some other applications, like `Ecto`, already being started then automatically starting `Money.ExchangeRates.Supervisor` may not work since your `Ecto.Repo` is unlikely to have already been started.

In this situation the appropriate way to configure the exchange rates retrieval service is the following:

1. Set the configuration key `exchange_rate_service` to `false` to prevent automatic startup of the service.

2. Configure your `api_module`, `callback_module` and any other required configuration as appropriate

3. In your client application code, add the `Money.ExchangeRates.Supervisor` to the `children` configuration of your application.  For example, in an application that uses `Ecto` and where your `callback_module` is designed to save exchange rates to a database, your application may would look something like:

```elixir
defmodule Application do
  use Application

  def start(_type, _args) do
    import Supervisor.Spec

    children = [

      # Start your repo first so that it is running before your
      # exchange rates callback module is called
      supervisor(MoneyTest.Repo, []),

      # Include the Money.ExchangeRates.Supervisor in your application's
      # supervision tree.  This supervisor will start the child process
      # Money.ExchangeRates.Retriever
      supervisor(Money.ExchangeRates.Supervisor, [])
    ]

    opts = [strategy: :one_for_one, name: Application.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

**Comment by aphillipo** [comment]
This of course is a great solution!  Thanks so much for your help!
