### ISSUE TITLE
Retrieve Exchange Rates Blocks Startup

### ISSUE THREAD

**Issue by aphillipo** [kipcole9/money#18]
Hi Kip!  Hope all is good.  Would you accept a pull request that uses Task.async for retrieving exchange rates?  The current situation is that app startup can be blocked waiting for Exchange rates to download should the service be taking a while (like it is now).

Let me know and I'll send you a pull request!

**Comment by kipcole9** [comment]
Andrew, I’ve been trying to figure out the right strategy here.  The current contract is that exchange rates are considered available as soon as the app starts and its an error condition if they aren’t.

But the downside is, as you say, that the service stalls until rates are available.

Let me think it through again and see if there’s a better way all around.

**Comment by aphillipo** [comment]
Well there should be if it doesn't exist a rate downloaded, but the function calls should not block startup every time.  It's on the developer to handle the no exchange rates case or provide default values in code should they not exists.

I would worry about deployment if the service blocks the application being available!  Sorry of this!

**Comment by kipcole9** [comment]
Andrew, I got it - and you’re right.  :-)  Will get this sorted over the weekend.  I knew that part smelled.  Time to fix it properly!

**Comment by kipcole9** [comment]
Andrew, have implemented the changes but I need to revisit my test strategy (which is also a good thing).  Basically here's how it goes - let me know if this works for you or if I should try another direction.

* At process initialisation, an initial retrieval is schedule to run in `n` milliseconds.  `n` defaults to 100 milliseconds and the value is set in the config key `:delay_before_first_retrieval`.  If this value is anything other than a positive integer then no first retrieval is performed.

* A new function, `Money.ExchangeRates.retrieve/0` is introduced which will force a retrieval on demand.  It still does this by sending a message to `Money.ExchangeRates.Retriever` process so it doesn't block and it decouples errors and exceptions from your main app.

I'll get the tests cleaned up by the end of the weekend if not before.

**Comment by kipcole9** [comment]
[Release 0.4.0](https:://hex.pm/packages/ex_money) contains the changes you rightly requested.  From the changelog:

## Changelog for Ex_Money v0.4.0  July 3,  2017

### Breaking Change

It's a breaking change but not a huge one.  `Money.ExchangeRates.Retriever` had a nasty code smell - it was retrieving rates during the initialisation of the process which had nasty side-effects if the retrieval stalled or crashed.  The new and improved strategy uses `Process.send_after/3` in the `init/1` function with a configurable delay before that first retrieval.

The configuration key is `:delay_before_first_retrieval` with a default of 100 milliseconds.  If set to anything other than a positive integer then the initial retrieval is not done - retrieval commences with the next cycle of the configured `:retrieve_every` interval.

For library users the key consideration here is that exchange rates cannot be assumed to be available when your application starts.

### Enhancements

* A new function `Money.ExchangeRates.retrieve/0` is available to schedule rate retrieval immediately.

* A new function `Money.ExchangeRates.rates_available?/0` that returns `true` if rates are available and `false` otherwise.
