### ISSUE TITLE
Created and retrieved structs do not match

### ISSUE THREAD

**Issue by ryanwinchester** [kipcole9/money#23]
In all of my tests when comparing a created `%Money{}` from the same one retrieved from DB, the comparison is off. 

Something like:

```elixir
test "list_entries/0 returns all entries" do
  entry = entry_fixture()
  assert Ledger.list_entries() == [entry]
end
```

Ends up failing because:

```elixir
# Created from Money.new(42, :USD)
%Money{currency: :USD, amount: %Decimal{sign: 1, coef: 42, exp: 0}}
# After saved, then fetched from DB
%Money{currency: :USD, amount: %Decimal{sign: 1, coef: 4200000000, exp: -8}}
```

An ideas why the difference?

**Comment by kipcole9** [comment]
Ryan, the `Decimal` type will manage coefficient and exponent in ways that mean a simple `==` isn't a reliable way to compare two `%Money{}`.  I'd suggest using `Money.cmp/2` or `Money.compare/2` which is the same approach taken by the underlying `Decimal` library.  For example:

```elixir
iex(1)> x = %Money{currency: :USD, amount: %Decimal{sign: 1, coef: 42, exp: 0}}
#Money<:USD, 42>
iex> y = %Money{currency: :USD, amount: %Decimal{sign: 1, coef: 4200000000, exp: -8}}
#Money<:USD, 42.00000000>
iex> Money.compare x, y
0
iex(4)> Money.cmp x, y    
:eq
```
In the Ecto case its because the precision of `money_with_currency` is `decimal(20,8)` the 8 digits of `0` decimal is being stored and retrieved.  With your example `Money.new(42, :USD)` there is no decimal precision.  Hence the underlying representation of the `Decimal` amount is different - even though they will compare to be equal.

**Comment by kipcole9** [comment]
On the master branch on GitHub I have added a function `Money.reduce/1` which will call `Decimal.reduce/1` on the underlying amount.  For the example case above you could use it to give a higher likelihood of equality with `==`.  For example:

```elixir
iex> x = %Money{currency: :USD, amount: %Decimal{sign: 1, coef: 42, exp: 0}}
#Money<:USD, 42>
iex> y = %Money{currency: :USD, amount: %Decimal{sign: 1, coef: 4200000000, exp: -8}}
#Money<:USD, 42.00000000>

# Comparison will fail because of the differing coefficient and exponents
# even though `Money.cmp` will return `:eq`
iex> x == y
false

# Money.reduce will simplify the coefficient and exponent
iex> y = Money.reduce(x)
#Money<:USD, 42>

# So the comparison will now work
iex> x == y
true
```

**Comment by ryanwinchester** [comment]
Thanks, I guess there is no avoiding getting more verbose in my test assertions 😭

the reasons make sense though, thanks. I think will use `Money.cmp/2`
