### ISSUE TITLE
Change openexchangerate to a free service?

### ISSUE THREAD

**Issue by Schultzer** [kipcole9/money#24]
Hi @kipcole9 

I was wondering if you are interested in using an alternative to [openexchangerates.org](https://openexchangerates.org/)
maybe Yahoo there offers 153 currencies.

I made an example on how to build a site like [openexchangerates.org](https://openexchangerates.org/) and [fixer.io](http://fixer.io/).

You can check it out at [fexr.org](https://fexr.org)
and all the code is located at

https://github.com/Schultzer/fexr
https://github.com/Schultzer/fexr_yahoo
https://github.com/Schultzer/fexr_imf

**Comment by kipcole9** [comment]
@Schultzer, looks good!  More than happy to support multiple exchange rate retrievers.  In fact [ex_money](https://hex.pm/packages/ex_money) supports plugging in your own favourite retriever.  It just happens I implemented one for  [Open Exchange Rates](http://openexchangerates.org) but its easy to implement your own.  I think the docs are pretty clear but in essence:

1. Define a module that implements the `Money.ExchangeRates` behaviour
2. This behaviour defines one function called `get_latest_rates/1` that takes as its argument an app_id the could be anything but it typically an api key for some exchange rates service
3 `get_latest_rates` should return `{:ok, rates_map}` or `{:error, reason}`
4.  `rates_map` should return atom keys that are valid IS04217 currency codes and the values should be `%Decimal{}`.
5. Configure [ex_money](https://hex.pm/packages/ex_money) to use your retrieval module by setting the config key   `api_module:` to the name of your module.  For example:
    config :ex_money,
      exchange_rate_service: true,
      api_module: Fexr.Money.ExchangeRateRetriever

That's it, you should be good to go.  Since you've done the hard work to make your api look similar/same to open exchange rates, I suspect you can copy https://github.com/kipcole9/money/blob/master/lib/money/exchange_rates/open_exchange_rates.ex and with minor modifications have your own module in no time.

I'm open to including additional retrievers in [ex_money](https://hex.pm/packages/ex_money) but I suspect additional retrievers should be in their own package so that release cycles aren't dependent.

**Comment by Schultzer** [comment]
@kipcole9 As how I understand the code it only gets rates from USD?
I'm not sure about this but wouldn't it be better to get the base from the money type we want to convert instead of assuming it's USD?

**Comment by kipcole9** [comment]
@Schultzer ex_money separates the retrieval/provision of exchange rates from the conversion function.  There are a few reasons for this:

1. Exchange rates api's provide updates on a non-realtime basis (I'm not writing a trading platform :smile:) so retrieving rates on a configurable periodic basis seems a reasonable policy

2. I didn't want to require an api call to an external service for each or any conversion function

3. For many conversions, the cross rates calculation preserves precision on a round trip conversion.  I accept that ex_money does not provide a guarantee on this since the exchange rate is provided as a float and hence mult/div of a float and a decimal necessarily introduces the risk of loss of precision.

If this strategy doesn't fit your requirements, but other parts of ex_money do suit your needs, you can provide your own rates map to the conversion function.  The signature for the `convert/3` is:

```
def to_currency(money, to_currency, rates \\ Money.ExchangeRates.latest_rates())
```

So you can provide a map of conversion rates that could use the base rate of your choice that may be better at preserving precision on the conversion.

I'm very open to improving the exchange rates and conversion mechanisms if you have thoughts and ideas that could reasonable support the design principles of (1) and (2) above.
