### ISSUE TITLE
Adhere to the Ecto.Type specs in the :map one

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#38]
Currently the Ecto.Type implementations with of the `:map` type might return errors in a different format than `:error` for `cast/1`. Also I'm not sure if `cast/1` should expect that the currency is valid.

**Comment by kipcole9** [comment]
Fair observation, both the composite type for Ecto and the `:map` type for MySQL should at least honour the same contract.

I think `cast/1` should validate the currency code since it is intended to return a valid result.  Clearly the `:map` type currently does not do that.

I will also validate that the returns for `cast/1` are consistent with the `@behaviour` to be `{:ok, result}` or `:error`.

**Comment by LostKobrakai** [comment]
Yeah, the composite type seems to be correct in that regard.

**Comment by kipcole9** [comment]
Updated in master.  Delegates `cast/1` from `Money.Ecto.Map.Type` to `Money.Ecto.Composite.Type` to ensure identical behaviour and remove duplicated code. Updated tests to have better coverage of both adapter types.  Likely issue an updated release candidate tomorrow so any other observations much appreciated.
