### ISSUE TITLE
The spec for Money.new/2 changed, breaks Money.from_float!/2

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#48]
With 2.0 the spec for `Money.new/2` changed (quite suprisingly) to `:: Money.t` instead of `:: {:ok, Money.t} | {:error, any()}`. I don't think that's a good idea and it promptly breaks `Money.from_float!`.

**Comment by kipcole9** [comment]
Fixed and issues on hex as version 2.0.3. Note from the changelog below.  I don't now how I screwed up the spec but its good now.

### Bug Fixes

* Fixes the typespec for `Money.new/2` and revises several other typespecs.  Added a dialyzer configuration.  Since `Money.new/2` allows flexible (probably too flexible) order or arguments, the typespec does not fully match the function implementation and Dialyzer understandably complains.  However the value of a typespec as documentation argues against making the typespec formally correct.  This will be revisited for Money 3.0.

**Comment by LostKobrakai** [comment]
I might have been inaccurate in describing my issue, but it's not only the spec, which was incorrect, but also the implementation (which is the reason `Money.from_float!` doesn't work):

https://github.com/kipcole9/money/blob/master/lib/money.ex#L115-L132

There are clauses which return a plain Money struct.

**Comment by kipcole9** [comment]
Ah. Hmmm.  Not good.  Legacy of the early days of the lib.  Changing `new/2` to return `{:ok, money}` would be a breaking change and would need a 3.0 release.  And that feels too fast.  I have updated `from_float/2` to play correctly with `new/2` as it currently stands.

So I propose fixing `from_float!/2` for now and changing `new/2` to return `{:ok money}` in release 3.0.  As well as deprecate it in the next release.

Its that workable for you?

**Comment by LostKobrakai** [comment]
Yeah, I'm mostly using new! anyways. But I'd suggest updating the spec here as well so it's reflecting the correct returned values (`t | {:error, …}`).

**Comment by LostKobrakai** [comment]
`from_float/2` has the same spec mismatch

**Comment by kipcole9** [comment]
Apologies for the screw-up on this.  Published 2.0.4 on hex and added doctests.
