### ISSUE TITLE
Subunit calculation not right in COP

### ISSUE THREAD

**Issue by danschultzer** [kipcole9/money#49]
We have a problem where subunit calculation doesn't work for Colombian Pesos. I spend a while trying to figure out if the error was upstream or what went wrong. It's actually because CLDR provide [customary, and not actual subunit digits](https://sourceforge.net/p/icu/mailman/message/36023202/).

So for [`to_integer_exp`](https://github.com/kipcole9/money/blob/c803789afe413082511121a722b842a0df9e253c/lib/money.ex#L1246) and [`from_integer`](https://github.com/kipcole9/money/blob/c803789afe413082511121a722b842a0df9e253c/lib/money.ex#L1292) to work as expected, the currency information should be pulled from the ISO source itself: https://www.currency-iso.org/dam/downloads/lists/list_one.xml

The actual formatting itself could be done with the CLDR information (I assume that it's 0 in CLDR because centavos are not used when dealing with costs in Colombia even though it exists).

wdyt @kipcole9?

**Comment by kipcole9** [comment]
If I understand correctly, the is a formal subunit, the _centavo_ that has no *cash* equvalent (there being no notes or coins for it) but it can be used for accounting purposes.  If this is a correct understanding then given the currency struct as defined in CLDR:
```elixir
 %Cldr.Currency{
   cash_digits: 0,
   cash_rounding: 0,
   code: "COP",
   count: %{one: "Colombian peso", other: "Colombian pesos"},
   digits: 0,
   name: "Colombian Peso",
   narrow_symbol: "$",
   rounding: 0,
   symbol: "COP",
   tender: true
 }
```
We would change that (in some manner and at some time to be determined) to:
```elixir
 %Cldr.Currency{
   cash_digits: 0,
   cash_rounding: 0,
   code: "COP",
   count: %{one: "Colombian peso", other: "Colombian pesos"},
   digits: 2,
   name: "Colombian Peso",
   narrow_symbol: "$",
   rounding: 2,
   symbol: "COP",
   tender: true
 }
```
Meaning that `:cash_digits` and `:cash_rounding` don't change but `:digits` and `:rounding` do.

I would:

1. Change Cldr data.  I'm not comfortable with this since it introduces a pretty high maintenance burden and technical debt for when new releases come out.  And it might be unexpected for other consumers.

2. Provide a means to customise currency definitions at compile time.  This way you can redefine COP for your use.  Its compiled in and therefore your application code doesn't have to change.

3. Add `:rounding` and `:digits` parameters to `Cldr.Number.to_string/2`, Cldr.Number.round/2`, `Money.round/1`, `Money.to_string/2` and `Money.to_integer_exp/1`.  This is more flexible and there is an expectation from the Cldr docs that the API should do this.  Its not too difficult to do - but I have always worried that it another potential source of error - different digits and rounding in different places.

So in many respects I like (2) the best.  Although Cldr does expect you should be able to specify digits and rounding in the formatting API so perhaps thats your requirement too?

Your thoughts @Schultzer ?

**Comment by danschultzer** [comment]
I don't think ex_money should rely on the CLDR data for any sort of conversions, calculations, etc. It should be used exclusively for formatting.

An example would be someone using this library to make a charge with Stripe. They will create a new money struct `Money.new(2_000, "COP")`, then get the integer amount with `Money.to_integer_exp(money)`. They will expect that 2,000 COP has been charged, but in fact only COP 20 will have been charged.

Then there's what we've experienced with `from_integer`. We pull a subunit amount of 2_000_00, and expect COP 2,000 to be shown, but COP 200,000 is shown instead. We've applied a fix, but I do think it's something ex_money should handle instead. I don't know if other currencies will have similar issue (we discovered the issue in production).

I suggest that that the information is pulled directly [from the ISO organization](https://www.currency-iso.org/dam/downloads/lists/list_one.xml), and used for the money struct. When there's any sort of formatting it'll use the CLDR data (so in the case of COP it'll always show without centavos when formatted). `Cldr.Currency` will remain unchanged, but Money will rely on ISO data for correct handling of amounts.

**Comment by danschultzer** [comment]
Looking at this, it shouldn't require too much work actually.

The ISO digits should be compiled in, and then it's just the following two places that should not use `Cldr.Currency`.

https://github.com/kipcole9/money/blob/c803789afe413082511121a722b842a0df9e253c/lib/money.ex#L1294
https://github.com/kipcole9/money/blob/c803789afe413082511121a722b842a0df9e253c/lib/money.ex#L1253

Since the digits are not used for this purpose in other place it seems to be a fix that won't affect much. E.g. it's not necessary in the following because it's just formatting:

https://github.com/kipcole9/money/blob/c803789afe413082511121a722b842a0df9e253c/lib/money.ex#L1047

**Comment by kipcole9** [comment]
Appreciate you digging in and making suggestions, its very helpful.

The digital definition is also used in `Cldr.Numbers`  which is what powers `Money.to_string/1` under the covers.  Not relevant to your needs for sure.

My example above was not to focus on CDLR itself, just on the structure of a `%Currency{}` struct.  Which suggests that changing `:digits` and `:rounding` need to be changed.

I still think there is a need to be able to differentiate between `:cash` and `:accounting` conversions since for `:cash` there is no _centavo_ but the default, as is the case throughout the CLDR library, is `:accounting`.

I don't think its a big change at all as you say - I just want to make it the right change, easily maintained.

I believe I can deliver a proof-of-concept for you in the next 24 hours.  If that ok timing for you?

**Comment by kipcole9** [comment]
Oh, also, important to say.  `Money` doesn't use CLDR for anything to do with math or conversions.  None at all.

CLDR is used only for:

1. Formatting via `Money.to_string/2`
2. Rounding a money amount (also called by Money.to_string/2`
3. Exporting a money amount thought `Money.to_integer_exp/1` but only because it rounds because it has to
4. `Money.from_integer/2` because it needs to look up the exponent (`:digits`)
5. `Money.split/2` because it also has to round

I know you know that but I just wanted to be clear that there is no involvement of CLDR in anything to do with calculations, math, conversions, exchange rates at all.

**Comment by danschultzer** [comment]
Yeah, no hurry, we got this in control for the next while so take you time to figure out what's the best way to handle this.

It would be great if we can differentiate the two. `:cash` and `:accounting` makes sense. I think we're good as long as it's clear that `:accounting` is international standard (used by banks, businesses, etc), and `:cash` is customary format.

Another thought I had is that maybe `to_integer_exp` and `from_integer` should be renamed to make it more clear what it actually is. `to_subunits` and `from_subunits` or even `to_integer(money, :subunits)` or something like that. I don't mind the way it is now, but maybe it'll be more explicit to talk about `subunits`.

Also, good to be reminded that CLDR isn't really used for any calculations :)

**Comment by kipcole9** [comment]
## Progress update and proposed API

### Augment CLDR data
[cldr](https://github.com/kipcole9/cldr) master now includes `:iso_digits` in the currency map that is part of a locale definition.   From the changelog:

* Adds `:iso_digits` to the currency data maintained in CLDR.  Cldr currency data does not always align with the ISO definition of a currency - notable for digits (subunit) definitions.  For example, the Colombian Peso has an official subunit of the _pesavo_.  One hundred _pesavos_ equals one peso.  There are no notes/cash/coins for the _centavo_ but it is an offical part of the currency and its important to be maintained for financial transactions.

* Adds a `Mix` task to download the ISO currency data that is used during locale consoldiation to include ISO currency digits (subunits) in the currency definition.

### Next steps

* [cldr_numbers](https://github.com/kipcole9/cldr_numbers)  will be updated to add the `:iso_digits` field to the `Cldr.Currency` struct

* [cldr_numbers](https://github.com/kipcole9/cldr_numbers) will be updated to add an additional flag when formatting.  Today there is a boolean flag `:cash` which determines whether to format according to `:cash` or `:accounting`.  I will deprecate this flag and use `:currency_type` which can be either of `:cash`, `:accounting` or `:iso`.  The default will remain `:accounting`.

* [money](https://github.com/kipcole9/money) will be changed such that `Money.to_integer_exp/1` and `Money.from_integer/2` use `:iso` as the currency definition by default.  

* An optional argument will be added to `Money.to_integer_exp/1` to allow for alternative subunit interpretation

### Upgrading

I will issue a new version of Money, version 1.3.  It will depend on the new versions of `cldr` and `cldr_numbers` so a simple `mix deps.update ex_money` should take care of it.

Note that this will be added to `cldr` version 1.4 which also includes a `cldr compiler` that detects locale configuration changes and automatically recompiles the relevant parts of Cldr.

**Comment by danschultzer** [comment]
Cool! `:iso_digits` is great for clarity, and with the listed steps, I understand why you want to have it as part of the CLDR data.

**Comment by kipcole9** [comment]
I have updated `cldr_numbers` and `money`.  I also had to update `cldr` to `1.4.0-rc.2`.  If you:
```
def deps() do
 {:ex_money, "2.1.0-rc.0"}
end
```
Then:
```
mix deps.update money
```
You should result in the correct versions of `cldr`, `cldr_numbers` and `money`.  I have updated `Money.to_integer_exp/2` and `Money.from_integer/2` to use `:iso_digits`.  I added some tests to verify.

These are release candidates but I wanted to get you something you could review, test, and comment on as quickly as possible.

**Comment by danschultzer** [comment]
Works as expected. I've removed our temporary patch and will push to production shortly 👍

**Comment by kipcole9** [comment]
Great, thanks for the feedback.  Unless some other issues crop up I'll move from RC to final release tomorrow.  I'll leave the issue open until then.

**Comment by danschultzer** [comment]
So far, no issues in production.

**Comment by kipcole9** [comment]
`ex_money` [version 1.2.0 is released on hex](https://hex.pm/packages/ex_money).  Thanks for the collaboration and patience.

**Comment by kipcole9** [comment]
A final note to document the digit (subunit) differences between Cldr and ISO.  There are 36 currencies with differences, including the now familiar `COP`.  I note that there are also 300 (Cldr currencies) - 178 (ISO currencies) = 212 Cldr currencies that have `:iso_digits` set to `nil` because they have no ISO 4217 equivalent in current use. These are, as best I can tell, historic currency codes like those in use in EU members before currency integration - but there are numerous others as well.

I have a proposal for discussion you may care to contribute to at [this issue](https://github.com/kipcole9/money/issues/50)
```elixir
%{
  XBB: %{digits: 2, iso_digits: 0},
  GYD: %{digits: 0, iso_digits: 2},
  MGA: %{digits: 0, iso_digits: 2},
  RSD: %{digits: 0, iso_digits: 2},
  PKR: %{digits: 0, iso_digits: 2},
  XPT: %{digits: 2, iso_digits: 0},
  ALL: %{digits: 0, iso_digits: 2},
  COP: %{digits: 0, iso_digits: 2},
  AMD: %{digits: 0, iso_digits: 2},
  SLL: %{digits: 0, iso_digits: 2},
  SOS: %{digits: 0, iso_digits: 2},
  MNT: %{digits: 0, iso_digits: 2},
  UZS: %{digits: 0, iso_digits: 2},
  XBA: %{digits: 2, iso_digits: 0},
  XDR: %{digits: 2, iso_digits: 0},
  XAU: %{digits: 2, iso_digits: 0},
  KPW: %{digits: 0, iso_digits: 2},
  SYP: %{digits: 0, iso_digits: 2},
  LAK: %{digits: 0, iso_digits: 2},
  XBD: %{digits: 2, iso_digits: 0},
  MMK: %{digits: 0, iso_digits: 2},
  XSU: %{digits: 2, iso_digits: 0},
  XUA: %{digits: 2, iso_digits: 0},
  TZS: %{digits: 0, iso_digits: 2},
  MUR: %{digits: 0, iso_digits: 2},
  XBC: %{digits: 2, iso_digits: 0},
  XTS: %{digits: 2, iso_digits: 0}, 
  XPD: %{digits: 2, iso_digits: 0},
  LBP: %{digits: 0, iso_digits: 2},
  XXX: %{digits: 2, iso_digits: 0},
  IRR: %{digits: 0, iso_digits: 2},
  AFN: %{digits: 0, iso_digits: 2},
  YER: %{digits: 0, iso_digits: 2},
  IDR: %{digits: 0, iso_digits: 2},
  XAG: %{digits: 2, iso_digits: 0},
  IQD: %{digits: 0, iso_digits: 3}
}
```
