### ISSUE TITLE
General purpose cache out of Money.ExchangeRates.Retriever

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/money#52]
Currently `Money.ExchangeRates.Retriever` seems to be build to automatically warm the ets table as cache by periodical update and prefetching historical data. I've a few ideas for improving upon that.

* Make the `[…]retry_every` config name independent from the used API provider. The ets table is named, so there can only be one per node anyways.
* Make that config accept `false`, to disable the periodic updates
* Make the GenServer's interface default `config` to `Money.ExchangeRates.config()` so that `Money.ExchangeRates` and `Money.ExchangeRates.Retriever` get the same functional interface, if the config is not explicitly provided. Alternatively have a setting `retrieve_through_cache` so, `Money.ExchangeRates` calls the cache instead of the `api_module`.
* Add the possibility to use `:dets` instead of `:ets` for retaining the data beyond restarts.
* Add a setting to enable/disable API calls on cache fails

This would allow for:

* Piping all requests through a local cache before hitting the API.
* Having a manually updated cache without any ability to call the API on it's own.
* Persistant storage in the file system if needed

**Comment by LostKobrakai** [comment]
This could also enable this to be efficiently used: https://docs.openexchangerates.org/docs/etags

**Comment by kipcole9** [comment]
Thanks for the suggestions.  I'll dive into these suggestions with the intention to accept them unless there is some strong reason not to.  I have a 7 hour plane flight tomorrow - which is always good for development work.

**Comment by kipcole9** [comment]
I have pushed to master a commit which

*  extracts the cache to ExchangeRates.Cache, 
*  moved all retriever functions to ExchangeRates.retriever.  The API for `ExchangeRates.Cache`, `ExchangeRates.Retriever` and `ExchangeRates` is now consistent:  `latest_rates/0` and `historic_rates/1`. One for caching, one for API calling and one for deciding which one to return
*  will not schedule any retrieval if the `:retrieve_every` config key is not an integer (so could be `nil` or `:never` to be a symbolic representation

### Todo:

* Revisit the documentation
* Decide the right strategy for the public API of `Money.ExchangeRates.latest_rates/0` and Money.ExchangeRates.historic_rates/1`.  Return either a cached value or API value?

Comments welcome.

**Comment by kipcole9** [comment]
I have [pushed a new commit to master](https://github.com/kipcole9/money/commit/f09dcf3cce51b3c941ced5e0f041e5d5b8b0a04c) that addresses most of the comments above.  I'd appreciate your comments and suggestions.  The changelog entry is here for convenience.

## Changelog for Money v2.3.0

This is the changelog for Money v2.3.0 released on _, 2018.  For older changelogs please consult the release tag on [GitHub](https://github.com/kipcole9/money/tags)

This release is primarily a refactoring of the exchange rates service.  It separates the concerns of retrieval and caching.  It also normalises the api amongst the three modules `Money.ExchangeRates`, `Money.ExchangeRates.Retriever` and `Money.ExchangeRates.Cache`.  Each of these modules implements:

  * `latest_rates/0`
  * `historic_rates/1`

This makes it clear that rates can be retrieved through the cache or the service API.  The implementation in `Money.ExchangeRates` will return the cached value if available or will call the service API if not.

### To Do

* [ ] Setting `:exchange_rates_retrieve_every` to a non integer value raises an execption. We want to be able to set the to `:never` so that periodic scheduling is not performed

* [ ] The exchange rates service is required for retrieval since we call the external API from the service in order to have a separate process and supervision.  So we need to ensure its started when we do `Money.ExchangeRates.Retriever.latest_rates/0`

### Enhancements

* Print an informative message and raises at compile time if the configured json library appears to not be configured.

* Move exchange rate caching to its own module `Money.ExchangeRates.Cache`

* Move all exchange rates retrieval functions to `Money.ExchangeRates.Retriever`

* If the config key `:retrieve_every` is set to a non positive integer value then no periodic retrieval will be performed.  This allows the configuration of, for example:

```
config ex_money,
  exchange_rates_retrieve_every: :never
```

**Comment by kipcole9** [comment]
I have [committed to master](https://github.com/kipcole9/money) the final pieces that I believe address the original issue.  I plan to release this as `ex_money` version 2.3 over the weekend.  Appreciate the nudge @LostKobrakai - the resulting retriever implementation is much cleaner and more consistent.

### Changelog for Money v2.3.0

This is the changelog for Money v2.3.0 released on _, 2018.  For older changelogs please consult the release tag on [GitHub](https://github.com/kipcole9/money/tags)

This release is primarily a refactoring of the exchange rates service.  It separates the concerns of retrieval and caching.  It also normalises the api amongst the three modules `Money.ExchangeRates`, `Money.ExchangeRates.Retriever` and `Money.ExchangeRates.Cache`.  Each of these modules implements:

  * `latest_rates/0`
  * `historic_rates/1`

This makes it clear that rates can be retrieved through the cache or the service API.  The implementation in `Money.ExchangeRates` will return the cached value if available or will call the service API if not.

### Migration from earlier versions

* If your current configuration relies upon the default exchange rates retrieval occurring then from this release forward you will need to explicity specify the retrieval period.  The default value has been changed to `:never`. For example:

```
config :ex_money,
  exchange_rates_retrieve_every: 300_000
```

### Deprecation

* The configuration option `:auto_start_exchange_rate_service` is deprecated.  The service is always started since rates can be retrieved synchronously on demand via `Money.ExchangeRates.Retriever.latest_rates/0` or periodically as defined by the configuration option `:exchange_rates_retrieve_every`

### Enhancements

* Print an informative message and raises at compile time if the configured json library appears to not be configured.

* Move exchange rate caching to its own module `Money.ExchangeRates.Cache`

* Move all exchange rates retrieval functions to `Money.ExchangeRates.Retriever`

* Add `Money.ExchangeRates.Retriever.reconfigure/1` to allow reconfiguration of the exchange rates retriever.

* Add `Money.ExchangeRates.Retriever.config/0` to return the current retriever configuration.

* If the config key `:exchange_rates_retrieve_every` is set to an `atom` rather than an `integer` then no periodic retrieval will be performed.  This allows the configuration of the following, which is also the default:

```
config :ex_money,
  exchange_rates_retrieve_every: :never
```

* Use `etag`s in the `Money.ExchangeRates.OpenExchangeRates` api module when retrieving exchange rates from the service.

**Comment by kipcole9** [comment]
[Release 2.2.0 is now on hex](https://hex.pm/packages/ex_money).  The changelog is [here](https://hexdocs.pm/ex_money/changelog.html#content)
