### ISSUE TITLE
to_string formatting

### ISSUE THREAD

**Issue by snewcomer** [kipcole9/money#60]
From master

`Money.to_string Money.new("USD", "234.467")` results in `{:ok, "USD$234.467"}`

I'd be happy to put in a PR if this is not expected!

**Comment by snewcomer** [comment]
Same example as tests on master

![screen shot 2018-03-24 at 11 41 09 am](https://user-images.githubusercontent.com/7374640/37867598-68b9ac38-2f58-11e8-86da-7c0a7705e71f.png)

**Comment by snewcomer** [comment]
Huh so we are both getting the same results.  I don't have them as direct dependencies but digging into deps, it looks like the versions are the same for both.

Also, running the tests for `money` pass with `cldr_number` @ `1.3.0` and `1.3.1`.  Just to check, also passing when pointing `cldr_number` pointing to master.

A little baffled at the moment.  Here is a screenshot from trying out in iex when running tests.

![screen shot 2018-03-25 at 9 35 32 am](https://user-images.githubusercontent.com/7374640/37877423-e721fe42-300f-11e8-8df4-7aeb992c0356.png)

Also tried on a fresh app and got the same thing with...

![screen shot 2018-03-25 at 9 51 51 am](https://user-images.githubusercontent.com/7374640/37877578-2ce5e748-3012-11e8-9ac4-7333460227a1.png)

![screen shot 2018-03-25 at 9 52 13 am](https://user-images.githubusercontent.com/7374640/37877584-371a7166-3012-11e8-90f6-e2db7c743c06.png)

**Comment by kipcole9** [comment]
@snewcomer looks like I'm misunderstanding your observation.  I was looking at your original post which had:
```elixir
Money.to_string Money.new("USD", "234.467") results in {:ok, "USD$234.467"}
```
showing a result of `{:ok, "USD$234.467"}` which is most definitely unexpected since the number isn't rounded to 2 decimal places.  Thats the part I couldn't reproduce.

But looks like you're saying something else?  Looking at the screenshots I would say that those results are correct if you're using the default locale which is "en-001" (meaning global English). If you're saying "heh, that whole US$ thing isn't right for me" then its because you probably want the locale "en" which is American English.

For example:

```elixir
iex(1)> Cldr.get_current_locale
%Cldr.LanguageTag{
  canonical_locale_name: "en-Latn-001",
  cldr_locale_name: "en-001",
  extensions: %{},
  gettext_locale_name: nil,
  language: "en",
  locale: %{},
  private_use: [],
  rbnf_locale_name: "en",
  requested_locale_name: "en-001",
  script: "Latn",
  territory: "001",
  transform: %{},
  variant: nil
}
iex(2)> Money.to_string Money.new("USD", "234.467")
{:ok, "US$234.47"}
iex(3)> Money.to_string Money.new("USD", "234.467"), locale: "en"
{:ok, "$234.47"}
```
I'm also not helping the situation because `ex_money` defaults to locale `en-001` (the system default) in `:dev` but I have it set to `en` in `:test` which is why you are seeing different results.

If this is the correct analysis of what you're seeing then I'd suggest that. you configure "en" as your default locale.   Thats done by:

```elixir
config :ex_cldr,
  default_locale: "en"
```

in your `config.exs` or the relevant environment `.exs`.  Hopefully that helps!

**Comment by snewcomer** [comment]
Ah I'm sorry!  Yes, I was looking at the tests vs what I was seeing in my application and was confused by why the output was different.

Thanks for showing me what to do!
