### ISSUE TITLE
Cannot sum(money_with_currency)

### ISSUE THREAD

**Issue by vumanhcuongit** [kipcole9/money#62]
I'm using Postgres database with Ecto and I'd like to sum all values a column but getting this error.
```
** (Postgrex.Error) ERROR 42883 (undefined_function): function sum(money_with_currency) does not exist
```
Is there a way to sum all values of a field having type is money_with_currency?

**Comment by kipcole9** [comment]
In order to use the Postgres aggregate functions on `money_with_currency` you would need to decompose the composite column.  For example, in SQL, if you have a column called `price` that is a `money_with_currency` then you would
```sql
SELECT category, sum((price).amount) FROM items GROUP BY category
```
**NOTE** that this breaks one of the important design goals of `Money` which is to avoid the risk of mixing currencies.  The above code completely ignores currency codes and therefore there is a real risk of adding numbers that share no meaning.

A second approach, which I will investigate, is to create a user-defined Postgres aggregate function as described in https://www.postgresql.org/docs/9.5/static/xaggr.html  That would allow a more expressive approach to aggregate and provide protection against cross-currency arithmetic.

**Comment by vumanhcuongit** [comment]
@kipcole9 thanks for your info & support 👍

**Comment by kipcole9** [comment]
I've added a [commit that implements the sum function](https://github.com/kipcole9/money/commit/db8a3c430d744d40ece407b2282598b076997b13) for the `money_with_currency` type.  I need to add tests and so far the return result is not being cast properly to the `Money.t` type.  But as a proof of concept it seems appropriate.  Feedback is welcome while I work on getting the code ready for release.

**Comment by kipcole9** [comment]
I've added [a further commit](https://github.com/kipcole9/money/commit/557a3a49eacce34e51c767bf9ac0a4920142bdd8) that documents how to use the `sum` function and how to `order_by` correctly as well.  I'm going to close this issue since I think the master branch now reflects your original request.  I will consider other aggregate functions if requested.  Having just released version 2.4.0 I'm reluctant to release another version so soon so unless there is an urgent need I will hold off for a couple of weeks.

**Comment by vumanhcuongit** [comment]
perfect 💯

**Comment by kipcole9** [comment]
I have pushed [Money version 2.5.0](https://hex.pm/packages/ex_money) to hex.  It includes the migration and Postgres function that provides the `sum` aggregate.

**Comment by vumanhcuongit** [comment]
👍
