### ISSUE TITLE
Feature Request: a way to turn a Money object into its appropriate micro units.

### ISSUE THREAD

**Issue by coladarci** [kipcole9/money#72]
Would love to submit a pull to allow me to do something like this:

```
      iex> Money.new(:USD, 10.12) |> Money.to_micro_units()
      1012
```

(where we'd obviously want that to be dictated by the currency's settings).

I see reference in your docs to potentially having that knowledge internally, but there's no public method (as far as I can tell). Any direction on how I might be able to pull this off?

(Side note, this library is out of control and we are extremely grateful for your time. We are always looking to help in any way we can)

**Comment by kipcole9** [comment]
@coladarci Take a look at `Money.to_integer_exp/2`:
```elixir
iex> Money.new(:USD, "10.2") |> Money.to_integer_exp  
{:USD, 1020, -2, #Money<:USD, 0.0>}
```
Which returns the integer, the exponent and the remainder (if any) after appropriate currency rounding.

Hopefully the docs are explanatory enough:

### to_integer_exp/2

Returns a tuple comprising the currency code, integer amount, exponent and remainder

Some services require submission of money items as an integer with an implied exponent that is appropriate to the currency.

Rather than return only the integer, `Money.to_integer_exp` returns the currency code, integer, exponent and remainder.

The remainder is included because to return an integer money with an implied exponent the `Money` has to be rounded potentially leaving a remainder.

### Argument

* `money` is any `Money.t` struct returned by `Cldr.Currency.new/2`

### Notes

* Since the returned integer is expected to have the implied fractional digits the `Money` needs to be rounded which is what this function does.  The rounding is done in accordance with the data defined in CLDR.

### Example

      iex> m = Money.new(:USD, "200.012356")
      #Money<:USD, 200.012356>
      iex> Money.to_integer_exp(m)
      {:USD, 20001, -2, Money.new(:USD, "0.002356")}

      iex> m = Money.new(:USD, "200.00")
      #Money<:USD, 200.00>
      iex> Money.to_integer_exp(m)
      {:USD, 20000, -2, Money.new(:USD, "0.00")}

**Comment by coladarci** [comment]
Wow - the docs explain it well - and I did hunt for it and simply couldn't find any reference to it. I never thought of it as an integer version so that's probably why I had trouble.

Thanks a million.... we'll find another way to contribute!

**Comment by kipcole9** [comment]
Thanks for the encourage and support.  And glad you find the lib useful.  Working on crypto currency support for the next major release.
