### ISSUE TITLE
[question][feature] Why not use two columns in Ecto.Migrations instead of one?

### ISSUE THREAD

**Issue by Schultzer** [kipcole9/money#9]
Hi @kipcole9,

First of Thanks for this module ❤️

I was just wondering why not use two columns instead of one in Ecto.Migrations
in my use-case I use 

``` 
add :currency, :string
add :amount,   :integer
```

and then I can use the DB arithmetic functions and then I just have a function there formatting a Money struct from the currency and amount.

**Comment by kipcole9** [comment]
@schultzer, for Postgres `money` uses a composite type defined as:
```
CREATE TYPE public.money_with_currency AS (currency_code char(3), amount numeric(20,8))
```
For three reasons, the first of which meets the objective you asked about:

1. To preserve the opportunity to perform arithmetic operations at a database level at a precision that is, as I understand it, accepted in the financial community.  For example in the following we create a table with a `price_with_currency` data column called `price`, insert three rows then select the sum of the `prices`.  Note the syntax for accessing elements of a composite type: `(price).amount`.
```
CREATE TABLE product (price money_with_currency);
INSERT INTO product (price) VALUES (('USD', 10.0)), (('USD', 20.0)), (('USD',30.0));
SELECT SUM((price).amount) FROM product;

     sum     
-------------
 60.00000000
```
Of course its still important to make sure that arithmetic operations are only performed on `money_with_currency` columns with the same currency code, or that the amount is converted.  At an application level, this is something that `money` enforces.

2. Represent clearly that a `money` column must have a currency code and an amount - to ensure that we can't have an amount without a currency code.  The two can't be separated.

3. Its entirely possible, maybe even likely, that there may be more than one `money` column in a table.  By using a composite data type this becomes trivial:

```
CREATE TABLE ledger (debit money_with_currency, credit money_with_currency);
```
This would become more complicated if currency codes and amounts were created as separate columns.

Since `MySQL` doesn't support composite types, `money` uses a `json` column to try as best as possible to implement the same three objectives.  Its not great since `json` doesn't have a `decimal` type so the number is a string and to do database level arithmetic `CAST`ing is required.
